name: Go
on: [push, pull_request]

jobs:
  test:
    name: Go
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -v -cover ./...
